### ISSUE TITLE
adding image on readme

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg#1]
thank you so much for the model @charleygros !!!

could you please use the [following example template](https://github.com/ivadomed/mice_uqueensland_gm) to add an example image that works with this model? thanks!!

**Comment by charleygros** [comment]
Done in [ed9d6e1](https://github.com/ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg/commit/ed9d6e1d9f24697d62af48aea81139fcc4666367).
