### ISSUE TITLE
Add species in participants.tsv

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg#4]
![image](https://user-images.githubusercontent.com/2482071/111348984-1ce55380-8657-11eb-8491-4f62b5db3f87.png)

@mariehbourget can inform as she is currently working on a BEP to add this field

**Comment by mariehbourget** [comment]
This is still in discussion.

At the moment,  in microscopy BEP031, we are recommending to add the column `species` in the `participants.tsv` file. As for the values, we recommend using the string of the name from [NCBI Taxonomy](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi), see the end of this [section](https://docs.google.com/document/d/1Nlu6QVQrbOQtdtcRarsONbX5SrOubXWBvkV37LRRqrc/edit?ts=6043b94d#heading=h.wnuqa8w7cot3). 

This seems compatible with another description for the species value in a new BEP for [animal ephys](https://docs.google.com/document/d/1oG-C8T-dWPqfVzL2W8HO3elWK8NIh2cOCPssRGv23n0/edit#heading=h.7d523gb1n83u) which is `Binomial species name (genus)`. We have not received feedback yet from the animal ephys people on using the NCBI taxonomy.

To satisfy both description, I would go with `mus musculus` for mice.

**Comment by jcohenadad** [comment]
Thank you for the detailed response @mariehbourget !!

**Comment by alexfoias** [comment]
Fixed in `duke /projects/ivadomed/gm_dwi_exvivo/participants.json `and `duke/projects/ivadomed/gm_dwi_exvivo/participants.tsv`.

**Comment by jcohenadad** [comment]
@alexfoias not a mouse, pls see https://github.com/ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg/issues/6

**Comment by alexfoias** [comment]
fixed to human. I wasn't aware of the issue.

**Comment by mariehbourget** [comment]
If you want to follow the same kind of naming as mentioned above i.e. `Binomial species name (genus)` and `NCBI Taxonomy`, I think it should be `Homo sapiens`.
Note: in our BEP031, we recommend the species field only when different from Homo sapiens (but it is not finalized yet and could change in the future)

**Comment by alexfoias** [comment]
do we want to add that column at the end ? @mariehbourget @jcohenadad

**Comment by jcohenadad** [comment]
> do we want to add that column at the end ? @mariehbourget @jcohenadad

no

**Comment by alexfoias** [comment]
okay I removed the column. I think we can close the issue now.
