### ISSUE TITLE
README needed in dataset

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg#5]
![image](https://user-images.githubusercontent.com/2482071/111349198-4aca9800-8657-11eb-83ea-f787ab0d737b.png)

Otherwise we might "clean" it without knowing what it is/was used for.

**Comment by alexfoias** [comment]
Done is **duke/projects/ivadomed/gm_dwi_exvivo/README.txt**.

**Comment by jcohenadad** [comment]
for the record, here is the content of the README:
~~~
Dataset used to train model for https://github.com/ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg
~~~
we can close, thx alex
