### ISSUE TITLE
Dimensions are closer to human than mouse

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg#6]
data found here: /duke/projects/ivadomed/gm_dwi_exvivo  (supposedly the data used for this model):

![Screen Shot 2021-03-16 at 1 30 59 PM](https://user-images.githubusercontent.com/2482071/111353839-0ee60180-865c-11eb-89e4-fd04948615b2.png)

1.4cm R-L diameter is definitely closer to human than mouse. So I am suspicious that this model is for mouse. @charleygros ?

**Comment by jcohenadad** [comment]
The error on the naming of the model has been confirmed by the user: https://forum.spinalcordmri.org/t/error-when-running-sct-get-centerline/551/24?u=jcohenadad

So we need to rename this model.

**Comment by charleygros** [comment]
Stupid error from my side.
Repo n model files now renamed `model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg`.
