### ISSUE TITLE
Add comment on the release notes

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg#8]
It would be quite informative to note (even briefly, a 1-liner) what is different in the new releases of models. E.g. in https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/releases/tag/r20210331

**Comment by charleygros** [comment]
Done, see https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/releases/tag/r20210331
And will do in future, thanks
