### ISSUE TITLE
move data to git-annex

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg#9]
so we can version-track the dataset used for the training

**Comment by alexfoias** [comment]
would we host it on our internal git server ?

**Comment by jcohenadad** [comment]
yes

**Comment by alexfoias** [comment]
@jcohenadad are we talking on moving the complete repo (data+readme+gif file) on the internal git server ? Or just to move the https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/blob/main/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.pt and https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/blob/main/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.json to it ?

**Comment by jcohenadad** [comment]
only the data which are currently on duke

**Comment by jcohenadad** [comment]
@kousu maybe this would be a good test bench for our "drop git annex" experiment

**Comment by alexfoias** [comment]
could one of you (@jcohenadad or @charleygros ) please point me to where I can find the data on duke ? thanks

**Comment by charleygros** [comment]
> could one of you (@jcohenadad or @charleygros ) please point me to where I can find the data on duke ? thanks

Model trained on duke:projects/ivadomed/gm_t2_exvivo__20210331_223156.zip

Thanks Alex!!

**Comment by alexfoias** [comment]
@kousu I have to create a new repo. Are the info here https://github.com/neuropoly/data-management/blob/master/internal-server.md#new-repository up to date ?

**Comment by alexfoias** [comment]
@kousu not sure if you saw my previous message. Could you please answer my question from above ? thanks

**Comment by kousu** [comment]
No, sorry it got lost for me. 

Those instructions are right. Please make sure you pay attention to the [bootstrapping advice](https://github.com/neuropoly/data-management/blob/master/git-annex.md#global-git-annex-config) that is linked from there.

**Comment by alexfoias** [comment]
I followed the instructions from above and added `datasets/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg`
Here is the log : https://pastebin.com/4xrzhYYi

**Comment by alexfoias** [comment]
Maybe @kousu or @jcohenadad can validate I did it correctly.

**Comment by jcohenadad** [comment]
happy to look at it, can you post the syntax for me to check what you did?

**Comment by alexfoias** [comment]
I couldn't find a procedure for cheking new repos. I would suggest something based on [this](https://github.com/neuropoly/data-management/blob/master/internal-server.md#reviewing-pull-requests): 

```
git clone git@data.neuro.polymtl.ca:datasets/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg
git annex sync --content

#Then look at the branch to see if it looks right to you.

#To investigate what changed:
git log --stat master..HEAD # to see filenames
git log -p master..HEAD     # to see content, commit-by-commit
git diff master..HEAD       # to see content, overall

#Also, it's a good idea to run:

git annex whereis
```

**Comment by jcohenadad** [comment]
hum, git annex whereis and git log give me no output:

<details><summary>Terminal output</summary>

```console
julien-macbook:~/data $ git clone git@data.neuro.polymtl.ca:datasets/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg
Cloning into 'model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 20 (delta 1), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (20/20), 23.77 MiB | 7.25 MiB/s, done.
Resolving deltas: 100% (1/1), done.
julien-macbook:~/data $ cd model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/
julien-macbook:~/data/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg $ git annex sync --content
(merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)
commit 
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
ok
pull origin 
ok
push origin 
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 16 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 738 bytes | 738.00 KiB/s, done.
Total 6 (delta 2), reused 1 (delta 0)
To data.neuro.polymtl.ca:datasets/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg
   e22522a..4d42ecf  git-annex -> synced/git-annex
ok
julien-macbook:~/data/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg $ git annex whereis
julien-macbook:~/data/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg $ ll
total 48696
drwxr-xr-x    6 julien  staff       192 22 Apr 16:20 .
drwxr-xr-x  125 julien  staff      4000 22 Apr 16:20 ..
drwxr-xr-x   15 julien  staff       480 22 Apr 16:20 .git
-rw-r--r--    1 julien  staff        75 22 Apr 16:20 .gitattributes
-rw-r--r--    1 julien  staff        76 22 Apr 16:20 README
-rwxr-xr-x    1 julien  staff  24921200 22 Apr 16:20 gm_t2_exvivo__20210331_223156.zip
julien-macbook:~/data/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg $ git annex whereis gm_t2_exvivo__20210331_223156.zip 
julien-macbook:~/data/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg $ git log --stat master..HEAD
```

</details>

my main comment would be to no put the ZIP file, but the unpacked BIDS data directly. This is the whole purpose of the git-annexed BIDS dataset --> it can track versions.

**Comment by alexfoias** [comment]
I have extracted the zip contents in the repo.

**Comment by jcohenadad** [comment]
LGTM!

**Comment by kousu** [comment]
Looks good to me too, but I dropped the commit with the .zip in it for you, so you'll want to delete + reclone.

**Comment by alexfoias** [comment]
@kousu Is this merged ? can we close this issue ?

**Comment by kousu** [comment]
We can close it once everyone with a copy reclones it, or at least deletes it, to drop that .zip file from the record.

**Comment by alexfoias** [comment]
@charleygros can we close this issue ? @kousu is there a way to find about who cloned the repo ? thanks

**Comment by charleygros** [comment]
> 
> 
> @charleygros can we close this issue ? @kousu is there a way to find about who cloned the repo ? thanks

I think so yes!
